name: Angular CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-app:
    runs-on: ubuntu-latest
    name: Build Angular app

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install --legacy-peer-deps
      working-directory: StudentGradebookUI

    - name: Run build
      run: npm run build --if-present
      working-directory: StudentGradebookUI
