name: .NET Core CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: StudentGradebookWebAPI

    - name: Build
      run: dotnet build --no-restore
      working-directory: StudentGradebookWebAPI

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: StudentGradebookWebAPI
