name: .NET Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run .NET Tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' # Update this to the latest .NET 8.0 version

    - name: Restore dependencies
      run: dotnet restore
      working-directory: StudentGradebookTests

    - name: Build
      run: dotnet build --no-restore
      working-directory: StudentGradebookTests

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: StudentGradebookTests
